image: docker:latest

stages:
 - prepare-tree
 - build

services:
  - docker:dind
before_script:
  - apk --update add make cmake py-pip git
  - pip install docker-compose

nightly-prepare-tree:
  stage: prepare-tree
  script:
    - mkdir -p opt/xcsoar opt/xcsoar-ccache
    - docker run -v $(pwd)/opt/xcsoar:/opt/xcsoar -v $(pwd)/opt/xcsoar-ccache:/root/.ccache folken/xcsoar-build:latest xcsoar-update
  except:
    - tags
  artifacts:
    expire_in: 4 weeks
    when: always
    paths:
      - opt/xcsoar
      - opt/xcsoar-ccache

nightly-unix:
  stage: build
  script:
    - docker run -v $(pwd)/opt/xcsoar:/opt/xcsoar -v $(pwd)/opt/xcsoar-ccache:/root/.ccache folken/xcsoar-build:latest xcsoar-compile-unix
  except:
    - tags
  artifacts:
    expire_in: 4 weeks
    when: always
    paths:
      - opt/xcsoar/output/UNIX

nightly-android:
  stage: build
  script:
    - docker run -v $(pwd)/opt/xcsoar:/opt/xcsoar -v $(pwd)/opt/xcsoar-ccache:/root/.ccache folken/xcsoar-build:latest xcsoar-compile-android
  except:
    - tags
  artifacts:
    expire_in: 4 weeks
    when: always
    paths:
      - opt/xcsoar/output/ANDROID

nightly-pc:
  stage: build
  script:
    - docker run -v $(pwd)/opt/xcsoar:/opt/xcsoar -v $(pwd)/opt/xcsoar-ccache:/root/.ccache folken/xcsoar-build:latest xcsoar-compile-pc
  except:
    - tags
  artifacts:
    expire_in: 4 weeks
    when: always
    paths:
      - opt/xcsoar/output/PC
