image: docker:latest
services:
  - docker:dind
before_script:
  - apk --update add make cmake py-pip git
  - pip install docker-compose
nightly-unix:
  stage: build
  script:
    - mkdir -p opt/xcsoar opt/xcsoar-ccache
    - docker run -v $(pwd)/opt/xcsoar:/opt/xcsoar -v $(pwd)/opt/xcsoar-ccache:/root/.ccache folken/xcsoar-build:latest xcsoar-update
    - docker run -v $(pwd)/opt/xcsoar:/opt/xcsoar -v $(pwd)/opt/xcsoar-ccache:/root/.ccache folken/xcsoar-build:latest xcsoar-compile-unix
  except:
    - tags
  artifacts:
    expire_in: 4 weeks
    when: always
    paths:
      - opt/xcsoar
